apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-assessment-tool
  labels:
    app: code-assessment-tool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-assessment-tool
  template:
    metadata:
      labels:
        app: code-assessment-tool
    spec:
      containers:
      - name: code-assessment-tool
        image: code-assessment-tool:latest
        ports:
          - containerPort: 8000
        env:
          - name: WORKING_NAMESPACE
            value: "default"
          - name: SERVICE_ACCOUNT_NAME
            value: "default"
