apiVersion: v1
kind: Service
metadata:
  name: code-assessment-tool-service
  labels:
    app: code-assessment-tool
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007
  selector:
    app: code-assessment-tool
